bonds = [ # Acolyte
'I would die to recover an ancient relic of my faith that was lost long ago.',
'I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.',
'I owe my life to the priest who took me in when my parents died.',
'Everything I do is for the common people.',
'I will do anything to protect the temple where I served.',
'I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.',
# Charlatan
'I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.',
'I owe everything to my mentor – a horrible person who is probably rotting in jail somewhere.',
'Somewhere out there, I have a child who does not know me. I am making the world better for him or her.',
'I come from a noble family, and one day I will reclaim my lands and title from those who stole them from me.',
'A powerful person killed someone I love. Someday soon, I will have my revenge.',
'I swindled and ruined a person who did not deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.',
# Criminal
'I am trying to pay off an old debt I owe to a generous benefactor.',
'My ill-gotten gains go to support my family.',
'Something important was taken from me, and I aim to steal it back.',
'I will become the greatest thief that ever lived.',
'I am guilty of a terrible crime. I hope I can redeem myself for it.',
'Someone I loved died because of a mistake I made. That will never happen again.',
# Entertainer
'My instrument is my most treasured possession, and it reminds me of someone I love.',
'Someone stole my precious instrument, and someday I will get it back.',
'I want to be famous, whatever it takes.',
'I idolize a hero of the old tales and measure my deeds against them.',
'I will do anything to prove myself superior to my hated rival.',
'I would do anything for the other members of my old troupe.',
# Folk Hero
'I have a family, but I have no idea where they are. One day, I hope to see them again.',
'I worked the land, I love the land, and I will protect the land.',
'A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.',
'My tools are symbols of my past life, and I carry them so that I will never forget my roots.',
'I protect those who cannot protect themselves.',
'I wish my childhood sweetheart had come with me to pursue my destiny',
#Guild Artisan
'The workshop where I learned my trade is the most important place in the world to me.',
'I created a great work for someone, and then found them unworthy to receive it. I am still looking for someone worthy.',
'I owe my guild a great debt for forging me into the person I am today.',
'I pursue wealth to secure my love.',
'One day I will return to my guild and prove that I am the greatest artisan of them all.',
'I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.',
# Hermit
'Nothing is more important than the other members of my hermitage, order, or association.',
'I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.',
'I am still seeking the enlightenment I pursued in my seclusion, and it still eludes me.',
'I entered seclusion because I loved someone I could not have.',
'Should my discovery come to light, it could bring ruin to the world.',
'My isolation gave me great insight into a great evil that only I can destroy.',

]
