Flaws = [ # Acolyte
'I judge others harshly, and myself even more severely.',
'I put too much trust in those who would wield power within the hierarchy of my temple.',
'My piety sometimes leads me to blindly trust those that profess faith in my god.',
'I am inflexible in my thinking.',
'I am suspicious of strangers and expect the worst of them.',
'Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.',
# Charlatan
'I cannot resist a pretty face.',
'I am always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.',
'I am convinced that no one could ever fool me the way I fool others.',
'I am too greedy for my own good. I cannot resist taking a risk if there is money involved.',
'I cannot resist swindling people who are more powerful than me.'
'I hate to admit it and will hate myself for it, but I will run and preserve my own hide if the going gets tough.',
# Criminal
'When I see something valuable, I cannot think about anything but how to steal it.',
'When faced with a choice between money and my friends, I usually choose the money.',
'If there is a plan, I will forget it. If I do not forget it, I will ignore it.',
'I have a “tell” that reveals when I am lying.',
'I turn tail and run when things look bad.',
'An innocent person is in prison for a crime that I committed. I am okay with that.',
# Entertainer
'I will do anything to win fame and renown.',
'I am a sucker for a pretty face.',
'A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.',
'I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.',
'I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.',
'Despite my best efforts, I am unreliable to my friends.',
# Folk Hero
'The tyrant who rules my land will stop at nothing to see me killed.',
'I am convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.',
'The people who knew me when I was young know my shameful secret, so I can never go home again.',
'I have a weakness for the vices of the city, especially hard drink.',
'Secretly, I believe that things would be better if I were a tyrant lording over the land.',
'I have trouble trusting in my allies.',
# Guild Artisan
'I will do anything to get my hands on something rare or priceless.',
'I am quick to assume that someone is trying to cheat me.',
'No one must ever learn that I once stole money from guild coffers.',
'I am never satisfied with what I have – I always want more.',
'I would kill to acquire a noble title.',
'I am horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I am surrounded by rivals.',
# Hermit
'Now that I have returned to the world, I enjoy its delights a little too much',
'I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.',
'I am dogmatic in my thoughts and philosophy.',
'I let my need to win arguments overshadow friendships and harmony.',
'I would risk too much to uncover a lost bit of knowledge.',
'I like keeping secrets and will not share them with anyone.',
# Noble
'I secretly believe that everyone is beneath me.',
'I hide a truly scandalous secret that could ruin my family forever.',
'I too often hear veiled insults and threats in every word addressed to me, and I am quick to anger.',
'I have an insatiable desire for carnal pleasures.',
'In fact, the world does revolve around me.',
'By my words and actions, I often bring shame to my family.',
# Outlander
'I am too enamored of ale, wine, and other intoxicants.',
'There is no room for caution in a life lived to the fullest.',
'I remember every insult I have received and nurse a silent resentment toward anyone who has ever wronged me.',
'I am slow to trust members of other races, tribes, and societies.',
'Violence is my answer to almost any challenge.',
'Do not expect me to save those who cannot save themselves. It is natural that the strong thrive and the weak perish.',
# Sage
'I am easily distracted by the promise of information.',
'Most people scream and run when they see a demon. I stop and take notes on its anatomy.',
'Unlocking an ancient mystery is worth the price of a civilization.',
'I overlook obvious solutions in favor of complicated ones.',
'I speak without really thinking through my words, invariably insulting others.',
'I can not keep a secret to save my life, or the lives of others.',
# Sailor
'I follow orders, even if I think they are wrong.',
'I will say anything to avoid having to do extra work.',
'Once someone questions my courage, I never back down no matter how dangerous the situation.',
'Once I start drinking, it is hard for me to stop.',
'I cannot help but pocket loose coins and other trinkets I come across.',
'My pride will probably lead to my destruction.',
# Soldier
'The monstrous enemy which we faced in battle still leaves me quivering with fear.',
'I have little respect for anyone who is not a proven warrior.',
'I made a terrible mistake in battle that cost many lives—and I would do anything to keep that mistake secret.',
'My hatred of my enemies is blind and unreasoning.',
'I obey the law, even if the law causes misery.',
'I would rather eat my armor than admit when I’m wrong.',
# Urchin
'If I am outnumbered, I will run away from a fight.',
'Gold seems like a lot of money to me, and I will do just about anything for more of it.',
'I will never fully trust anyone other than myself.',
'I would rather kill someone in their sleep than fight fair.',
'It is not stealing if I need it more than someone else.',
'People who cannot take care of themselves get what they deserve.']
