Ideals = [ # Acolyte
'The ancient traditions of worship and sacrifice must be preserved and upheld.',
'I always try to help those in need, no matter what the personal cost.',
'We must help bring about the changes the gods are constantly working in the world.',
'I hope to one day rise to the top of the religious hierarchy of my faith.',
'I trust that my deity will guide my actions. I have faith that if I work hard, things wil go well.',
'I seek to prove myself worthy of the favor of my god by matching my actions against his or her teachings.',
# Charlatan
'I am a free spirit – no one tells me what to do.',
'I never target people who cannot afford to lose a few coins.',
'I distribute the money I acquire to the people who really need it.',
'I never run the same con twice.',
'Material goods come and go. Bonds of friendship last forever.',
'I am determined to make something of myself.',
# Criminal
'I do not steal from others in the trade.',
'Chains are meant to be broken, as are those who would forge them.',
'I steal from the wealthy so that I can help people in need.',
'I will do whatever it takes to become wealthy.',
'I am loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.',
'There is a spark of good in everyone.',
# Entertainer
'When I perform, I make the world better than it was.',
'The stories, legends, and songs of the past must never be forgotten, for they teach us who we are.',
'The world is in need of new ideas and bold action.',
'I am only in it for the money and fame.',
'All that matters are the smiles I bring to people when I perform.',
'Art should reflect the soul; it should come from within and reveal who we really are.',
# Folk Hero
'People deserve to be treated with dignity and respect.',
'No one should get preferential treatment before the law, and no one is above the law.',
'Tyrants must not be allowed to oppress the people.',
'If I become strong, I can take what I want—what I deserve.',
'There is no good in pretending to be something I am not.',
'Nothing and no one can steer me away from my higher calling.',
# Guild Artisan
'It is the duty of all civilized people to strengthen the bonds of community and the security of civilization.',
'My talents were given to me so that I could use them to benefit the world.',
'Everyone should be free to pursue his or her own livelihood.',
'I am only in it for the money.',
'I am committed to the people I care about, not to ideals.',
'I work hard to be the best there is at my craft.',
# Hermit
'My gifts are meant to be shared with all, not used for my own benefit.',
'Emotions must not cloud our sense of what is right and true, or our logical thinking.',
'Inquiry and curiosity are the pillars of progress.',
'Solitude and contemplation are paths toward mystical or magical power.',
'Meddling in the affairs of others only causes trouble.',
'If you know yourself, there’s nothing left to know.',
# Noble
'Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity.',
'It is my duty to respect the authority of those above me, just as those below me must respect mine.',
'I must prove that I can handle myself without the coddling of my family.',
'If I can attain more power, no one will tell me what to do.',
'Blood runs thicker than water.',
'It is my duty to protect and care for the people beneath me.',
# Outlander
'Life is like the seasons, in constant change, and we must change with it.',
'It is the responsibility of each individual to make the most happiness for the whole tribe.',
'If I dishonor myself, I dishonor my whole clan.',
'The strongest are meant to rule.',
'The natural world is more important than all the constructs of civilization.',
'I must earn glory in battle, for myself and my clan.',
# Sage
'The path to power and self-improvement is through knowledge.',
'What is beautiful points us beyond itself toward what is true.',
'Emotions must not cloud our logical thinking.',
'Nothing should fetter the infinite possibility inherent in all existence.',
'Knowledge is the path to power and domination.',
'The goal of a life of study is the betterment of oneself.',
#Sailor
'The thing that keeps a ship together is mutual respect between captain and crew.',
'We all do the work, so we all share in the rewards.',
'The sea is freedom-the freedom to go anywhere and do anything.',
'I am a predator, and the other ships on the sea are my prey.',
'I am committed to my crewmates, not to ideals.',
'Someday I will own my own ship and chart my own destiny.',
# Soldier
'Our lot is to lay down our lives in defense of others.',
'I do what I must and obey just authority.',
'When people follow orders blindly, they embrace a kind of tyranny.',
'In life as in war, the stronger force wins.',
'Ideals aren’t worth killing over or going to war for.',
'My city, nation, or people are all that matter.',
# Urchin
'All people, rich or poor, deserve respect.',
'We have to take care of each other, because no one else is going to do it.',
'The low are lifted up, and the high and mighty are brought down. Change is the nature of things.',
'The rich need to be shown what life and death are like in the gutters.',
'I help the people who help me-that is what keeps us alive.',
'I am going to prove that I am worthy of a better life.']
