traits = [ # Acolyte
'I idolize a particular hero of my faith, and constantly refer to their deeds and example.',
'I can find common ground between the fiercest enemies, empathizing with them and always working towards peace.',
'I see omens in every event and action. The gods try to speak to us, we just need to listen.',
'Nothing can shake my optimistic attitude.',
'I quote (or misquote) sacred texts and proverbs in almost every situation.',
'I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.',
'I have spent so long in the temple that I have little practical experience dealing with people in the outside world.',
# Charlatan
'I fall in and out of love easily, and am always pursuing someone.',
'I have a joke for every occasion, especially occasions where humor is inappropriate.',
'Flattery is my preferred trick for getting what I want.',
'I am a born gambler who cannot resist taking a risk for a potential payoff.',
'I lie about almost everything, even when there is no good reason to.',
'Sarcasm and insults are my weapons of choice.',
'I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.',
'I pocket anything I see that might have some value.',
# Criminal
'I always have a plan for what to do when things go wrong.',
'I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.',
'The first thing I do in a new place is note the locations of everything valuable-or where such things could be hidden.',
'I would rather make a new friend than a new enemy.',
'I am incredibly slow to trust. Those who seem the fairest often have the most to hide.',
'I do not pay attention to the risks in a situation. Never tell me the odds.',
'The best way to get me to do something is to tell me I cannot do it.',
'I blow up at the slightest insult.',
# Entertainer
'I know a story relevant to almost every situation.',
'Whenever I come to a new place, I collect local rumors and spread gossip.',
'I am a hopeless romantic, always searching for that "special someone."',
'Nobody stays angry at me or around me for long, since I can defuse any amount of tension.',
'I love a good insult, even one directed at me.',
'I get bitter if I am not the center of attention.',
'I will settle for nothing less than perfection.',
'I change my mood or my mind as quickly as I change key in a song.',
# Folk Hero
'I do judge people by their actions, not their words.',
'If someone is in trouble, I am always ready to lend help.',
'When I set my mind to something, I follow through no matter what gets in my way.',
'I do have a strong sense of fair play and always try to find the most equitable solution to arguments.',
'I am confident in my own abilities and do what I can to instill confidence in others.',
'Thinking is for other people. I prefer action.',
'I misuse long words in an attempt to sound smarter.',
'I get bored easily. When am I going to get on with my destiny?',
# Guild Artisan
'I believe that anything worth doing is worth doing right. I cannot help it – I am a perfectionist.',
'I am a snob who looks down on those who cannot appreciate fine art.',
'I always want to know how things work and what makes people tick.',
'I am full of witty aphorisms and have a proverb for every occasion.',
'I am rude to people who lack my commitment to hard work and fair play.',
'I like to talk at length about my profession.',
'I do not part with my money easily and will haggle tirelessly to get the best deal possible.',
'I am well known for my work, and I want to make sure everyone appreciates it. I am always taken aback when people have not heard of me.',
# Hermit
'I have been isolated for so long that i speak rarely, preferring gestures and also the occasional grunt',
'I am utterly serene, even in the face of disaster.',
'The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.',
'I feel tremendous empathy for all who suffer.',
'I am oblivious to etiquette and social expectations.',
'I connect everything that happens to me to a grand, cosmic plan.',
'I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.',
'I am working on a grand philosophical theory and love sharing my ideas.',
# Noble
'My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.',
'The common folk love me for my kindness and generosity.',
'No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.',
'I take great pains to always look my best and follow the latest fashions.',
'I do not like to get my hands dirty, and I will not be caught dead in unsuitable accommodations.',
'Despite my noble birth, I do not place myself above other folk. We all have the same blood.',
'My favor, once lost, is lost forever.',
'If you do me an injury, I will crush you, ruin your name, and salt your fields.',
# Outlander
'I am driven by a wanderlust that led me away from home.',
'I watch over my friends as if they were a litter of newborn pups.',
'I once ran twenty-five miles without stopping to warn to my clan of an approaching orc horde. I would do it again if I had to.',
'I have a lesson for every situation, drawn from observing nature.',
'I place no stock in wealthy or well-mannered folk. Money and manners will not save you from a hungry owlbear.',
'I am always picking things up, absently fiddling with them, and sometimes accidentally breaking them.',
'I feel far more comfortable around animals than people.',
'I was, in fact, raised by wolves.',
# Sage
'I use polysyllabic words that convey the impression of great erudition.',
'I have read every book in the greatest libraries of the world—or I like to boast that I have.',
'I amused to helping out those who are not as smart as I am, and I patiently explain anything and everything to others.',
'There is nothing I like more than a good mystery.',
'I am willing to listen to every side of an argument before I make my own judgment.',
'I . . . speak . . . slowly . . . when talking . . . to idiots, . . . which . . . almost . . . everyone . . . is . . . compared . . . to me.',
'I am horribly, horribly awkward in social situations.',
'I am convinced that people are always trying to steal my secrets.',
# Sailor
'My friends know they can rely on me, no matter what.',
'I work hard so that I can play hard when the work is done.',
'I enjoy sailing into new ports and making new friends over a flagon of ale.',
'I stretch the truth for the sake of a good story.',
'To me, a tavern brawl is a nice way to get to know a new city.',
'I never pass up a friendly wager.',
'My language is as foul as an otyugh nest.',
'I like a job well done, especially if I can convince someone else to do it.',

]
